### ISSUE TITLE
KeyError 'summary'

### ISSUE THREAD

**Issue by rinzes** [f4bio/sopel-rss#10]
.I did a .rssadd #swingtrader Long_Ideas http://seekingalpha.com/tag/long-ideas.xml

[sopel-rss] [INFO] added sqlite table "rss_1ec52e49392b57ca042f0b2ed3f2de77" for feed "Long_Ideas"
[sopel-rss] [INFO] added ring buffer for feed "Long_Ideas"
[sopel-rss] [INFO] added to channel "#swingtrader" rss feed "Long_Ideas" with url "http://seekingalpha.com/tag/long-ideas.xml"
Traceback (most recent call last):
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/tools/jobs.py", line 142, in _call
    func(self.bot)
  File "/home/znc/.sopel/modules/rss.py", line 305, in __update
    __updateFeed(bot, feedname, False)
  File "/home/znc/.sopel/modules/rss.py", line 314, in __updateFeed
    hash = __hashEntry(feedname + item['title'] + item['link'] + item['summary'])
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/feedparser.py", line 357, in __getitem__
    return dict.**getitem**(self, key)
KeyError: 'summary'

**Comment by rinzes** [comment]
I am also getting the same as above from the following url's:

http://seekingalpha.com/tag/ipo-analysis.xml
http://seekingalpha.com/feed.xml
http://seekingalpha.com/tag/short-ideas.xml

**Comment by RebelCodeBase** [comment]
Yes, I will address this issue with a general handling of rss item fields.
