### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by rinzes** [f4bio/sopel-rss#7]
Traceback (most recent call last):
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/tools/jobs.py", line 142, in _call
    func(self.bot)
  File "/home/znc/.sopel/modules/rss.py", line 305, in __update
    __updateFeed(bot, feedname, False)
  File "/home/znc/.sopel/modules/rss.py", line 314, in __updateFeed
    hash = __hashEntry(feedname + item['title'] + item['link'] + item['summary'])
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/feedparser.py", line 357, in __getitem__
    return dict.**getitem**(self, key)
KeyError: 'link'

**Comment by RebelCodeBase** [comment]
Again: I need more information to debug. What was the command that you used to add the feed?

**Comment by rinzes** [comment]
The command I use to add is the same as I provided. These are traceback errors I receive while viewing

**Comment by rinzes** [comment]
You can close this issue. I found the culpurt. 

https://nypost.com/news/feed/
