### ISSUE TITLE
Runtime error while adding feed

### ISSUE THREAD

**Issue by rinzes** [f4bio/sopel-rss#9]
This for your information.. It doesn't seem to effect anything. 

[sopel-rss] [INFO] added sqlite table "rss_906937582aedbd76a60bd98117b12cd3" for feed "RTR_Health"
[sopel-rss] [INFO] added ring buffer for feed "RTR_Health"
[sopel-rss] [INFO] added to channel "#globalnews" rss feed "RTR_Health" with url "http://feeds.reuters.com/reuters/healthNews"
Traceback (most recent call last):
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/tools/jobs.py", line 142, in _call
    func(self.bot)
  File "/home/znc/.sopel/modules/rss.py", line 305, in __update
    __updateFeed(bot, feedname, False)
  File "/home/znc/.sopel/modules/rss.py", line 324, in __updateFeed
    __config_save(bot)
  File "/home/znc/.sopel/modules/rss.py", line 97, in __config_save
    __saveHashesToDatabase(bot)
  File "/home/znc/.sopel/modules/rss.py", line 126, in __saveHashesToDatabase
    for feedname in bot.memory['rss']['feeds']:
RuntimeError: dictionary changed size during iteration

**Comment by RebelCodeBase** [comment]
Thanks, I've already noticed that, too. This happens, when the asynchronous updater is confronted with a changed dictionary of feeds after a feed has been deleted or added.
